DonacionMedicamentos.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace DonacionMedicamentos.Web.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

DonacionMedicamentos.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace DonacionMedicamentos.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

DonacionMedicamentos.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using DonacionMedicamentos.Web.Models.Layout;

namespace DonacionMedicamentos.Web.Controllers
{
    public class LayoutController : DonacionMedicamentosControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IUserNavigationManager userNavigationManager, 
            ILocalizationManager localizationManager,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _languageManager.CurrentLanguage,
                            Languages = _languageManager.GetLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }
    }
}

DonacionMedicamentos.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">
    <link rel="stylesheet" type="text/css" href="~/css/main.css">

    <title>DonacionMedicamentos</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body class="body">
    

    @Html.Partial("_TopBar")
    @RenderBody()

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        abp.localization.defaultSourceName = '@LocalizationSourceName';
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name.ToLower()'); //Localizing momentjs
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

DonacionMedicamentos.Web/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"> <img src="~/images/logo.png" width="100px" /> Donarg</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
                @if (Request.IsAuthenticated)
                {
                    <li class="dropdown pull-right">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            @Request.Cookies["UserData"]["NombreCompleto"]
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @if (Request.Cookies["UserData"]["User"] == "rol_person")
                                {
                                    @Html.ActionLink("Editar datos personales", "Edit", "Person")
                                }
                                else if (Request.Cookies["UserData"]["User"] == "rol_intermediary")
                                {
                                    @Html.ActionLink("Editar datos", "Edit", "Intermediary")
                                }
                            </li>
                            <li>
                                @Html.ActionLink("Cambiar contraseña", "ChangePass", "User")
                            </li>
                            <li class="divider"></li>
                            <li>
                                @Html.ActionLink("Cerrar Sesión", "Logout", "User")
                            </li>
                        </ul>
                    </li>
                }
                else
                {
                    Request.Cookies.Clear();
                    <li>
                        @Html.ActionLink("Registrarse", "Create", "Person")
                    </li>
                    <li>
                        @Html.ActionLink("Ingresar", "Login", "User")
                    </li>
                }
            </ul>
        </div>
    </div>
</div>